# Generated by Django 3.0.8 on 2020-07-19 18:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=30)),
                ('inicio', models.CharField(max_length=30)),
                ('punto1', models.CharField(max_length=30)),
                ('punto2', models.CharField(max_length=30)),
                ('punto3', models.CharField(max_length=30)),
                ('punto4', models.CharField(max_length=30)),
                ('punto5', models.CharField(max_length=30)),
                ('fin', models.CharField(max_length=30)),
            ],
            managers=[
                ('rutas', django.db.models.manager.Manager()),
            ],
        ),
    ]
